第２回課題提出
kiriaya/raisetech pull request #1
Opened 2023-11-07 13:45 UTC by kiriaya

2023-11-08 03:09 UTC, MasatoshiMizumoto requested changes
ありがとうございます！
正しくPRできてますね！
Markdownのプレビューってされてますかね？
正しく書かれているかはプレビューをしないとわからないので、確認しつつ書いてみてください！

指摘を入れてますので修正して再度pushまでやったらご連絡ください！
意味がわからない場合はどういう操作を想定しているかご自身の見解を質問でください！（こう思っているのですがあっていますか）

2023-11-08 03:09 UTC, MasatoshiMizumoto commented on lecture02.md
> +# 第２回課題 ＃
1行目は見出しの想定ですかね？
囲ったりはしないので行末を消してもらえますと！
```suggestion
# 第２回課題
```

2023-11-08 03:09 UTC, MasatoshiMizumoto commented on lecture02.md
> +1.git
1行目を見出し1にするならここは少し小さい見出しですかねー。
```suggestion
## git
```

2023-11-08 03:09 UTC, MasatoshiMizumoto commented on lecture02.md
> +
実施した事実だけではなく、こんな感じで学んだことみたいな部分もアウトプットすると良いかなと思いました！

```suggestion
- git clone リモートリポジトリをローカルへ移す
- 作業用のブランチ（分岐）を切ってから変更の後マージをする流れ
- git add ローカルリポジトリにてワークツリーからインデックスに移行
- git commit リポジトリに変更内容を登録（保存）するため
- git push 　ローカルからリモートへ反映

### 学んだこと

> 良かったこと、課題感、次のチャレンジなど

- hoge
- fuga
- hoe

```

2023-11-08 03:10 UTC, MasatoshiMizumoto commented
あとPR作成したときのコメント枠なんですが、これは掲示板とやメールと同じなので、
件名と連絡文は入れておきましょう！

2023-11-10 11:02 UTC, kiriaya commented
課題以外で不要なブランチ、ファイルを削除しました。ローカルと同期させて削除しました。

2023-11-10 12:06 UTC, MasatoshiMizumoto approved these changes
よくできました！
LGTM!

2023-11-10 14:32 UTC, merged